import type { Program } from "./types";

/**
 * Demo verisi — Sprint 1 prototipinden taşındı (Düzce'de 3 kişilik AI yazılım
 * girişimi "Nova AI Yazılım" senaryosu). Gerçek veri pipeline'ı (Supabase +
 * RAG) hazır olduğunda bu dosyanın yerini API çağrıları alacak.
 */
export const PROGRAMS: Program[] = [
  {
    id: "bigg",
    name: "TÜBİTAK 1512 BİGG",
    org: "TÜBİTAK",
    category: "kamu",
    categoryLabel: "Kamu Desteği",
    icon: "account_balance",
    typeLabel: "Hibe",
    hasAmount: true,
    amountText: "600.000",
    amountSub: "TL'ye kadar",
    curCode: "TRY",
    rate: "Hibe sermaye",
    status: "open",
    statusLabel: "Açık",
    deadlineText: "Son başvuru 15 Tem 2026",
    deadlineDays: 18,
    sourceLink: "tubitak.gov.tr",
    sourceHref: "https://www.tubitak.gov.tr",
    updated: "27 Haz 2026",
    elig: { state: "full", score: 100, label: "Tam uygun" },
    summary:
      "Yeni, teknoloji ve yenilik odaklı iş fikirleri olan girişimcilere geri ödemesiz sermaye desteği sağlar. İş planı ve proje sunumu ile başvurulur; başarılı projeler 1812 ile yatırım aşamasına taşınabilir.",
    criteria: [
      { icon: "school", label: "Eğitim", value: "Ön lisans+ mezun/öğrenci" },
      { icon: "memory", label: "Alan", value: "Teknoloji / yazılım" },
      { icon: "event", label: "Şirket yaşı", value: "Yeni veya kurulacak" },
      { icon: "flag", label: "Yerleşik", value: "Türkiye" },
    ],
    conditions: [
      {
        state: "met",
        text: "Kurucu ortak ön lisans/lisans/yüksek lisans öğrencisi veya mezunu",
        value: "3 kurucu da üniversite mezunu",
      },
      {
        state: "met",
        text: "Şirket kuruluş tarihi son 1 yıl içinde ya da başvuruda kurulacak",
        value: "Kuruluş < 1 yıl",
      },
      {
        state: "met",
        text: "Teknoloji tabanlı yenilikçi iş fikri",
        value: "Otonom bulut maliyet ajanı (AI)",
      },
      { state: "met", text: "Türkiye'de yerleşik girişimci", value: "Düzce, Türkiye" },
      {
        state: "action",
        text: "İş planı ve proje sunumu",
        value: "Gravio taslağı hazırladı",
        hint: "İş planı ve proje özeti taslağın hazır — Başvuru Hazırlığı ekranından indirip kişiselleştirebilirsin.",
      },
    ],
  },
  {
    id: "aws",
    name: "AWS Activate",
    org: "Amazon Web Services",
    category: "bulut",
    categoryLabel: "Bulut & Yazılım Kredisi",
    icon: "cloud",
    typeLabel: "Bulut Kredisi",
    hasAmount: true,
    amountText: "1.000–300.000",
    amountSub: "kredi tutarı",
    curCode: "USD",
    rate: "%100 bulut kredisi",
    status: "always",
    statusLabel: "Sürekli açık",
    deadlineText: "Sürekli başvuru",
    deadlineDays: null,
    sourceLink: "aws.amazon.com/activate",
    sourceHref: "https://aws.amazon.com/activate/",
    updated: "27 Haz 2026",
    elig: { state: "full", score: 95, label: "Uygun" },
    summary:
      "Erken aşama girişimlere AWS bulut altyapısı için kademeli ücretsiz kredi sağlar. İleri / yapay zekâ kullanımları için 300.000 dolara kadar çıkabilir; başvuru sürekli açıktır.",
    criteria: [
      { icon: "rocket_launch", label: "Aşama", value: "Erken aşama startup" },
      { icon: "memory", label: "Alan", value: "Teknoloji / AI" },
      { icon: "event", label: "Şirket yaşı", value: "< 10 yıl" },
      { icon: "public", label: "Bölge", value: "Global (TR dahil)" },
    ],
    conditions: [
      {
        state: "met",
        text: "Erken aşama, tüzel kişiliği olan girişim",
        value: "Yeni kurulmuş A.Ş.",
      },
      { state: "met", text: "Daha önce büyük çapta AWS kredisi almamış", value: "İlk başvuru" },
      {
        state: "met",
        text: "Teknoloji / yazılım ürünü geliştiriyor",
        value: "Bulut tabanlı AI ajanı",
      },
      {
        state: "action",
        text: "Hızlandırıcı/VC referansı üst kademeyi açar",
        value: "NVIDIA Inception ile güçlendirilebilir",
        hint: "NVIDIA Inception veya bir hızlandırıcı bağlantısı, AWS Activate'in üst kredi kademesine erişimi kolaylaştırır.",
      },
    ],
  },
  {
    id: "google",
    name: "Google for Startups",
    org: "Google Cloud",
    category: "bulut",
    categoryLabel: "Bulut & Yazılım Kredisi",
    icon: "cloud",
    typeLabel: "Bulut Kredisi",
    hasAmount: true,
    amountText: "350.000",
    amountSub: "'a kadar (2 yıl)",
    curCode: "USD",
    rate: "Bulut + topluluk",
    status: "always",
    statusLabel: "Sürekli açık",
    deadlineText: "Sürekli başvuru",
    deadlineDays: null,
    sourceLink: "cloud.google.com/startup",
    sourceHref: "https://cloud.google.com/startup",
    updated: "27 Haz 2026",
    elig: { state: "full", score: 92, label: "Uygun" },
    summary:
      "Yapay zekâ girişimlerine 2 yıl boyunca 350.000 dolara kadar Google Cloud kredisi, teknik destek ve mentorluk sağlar. AI-first girişimler için ayrı bir kademe sunar.",
    criteria: [
      { icon: "rocket_launch", label: "Aşama", value: "Tohum / erken" },
      { icon: "memory", label: "Alan", value: "AI-first" },
      { icon: "event", label: "Şirket yaşı", value: "< 5 yıl" },
      { icon: "public", label: "Bölge", value: "Global" },
    ],
    conditions: [
      {
        state: "met",
        text: "Yapay zekâ tabanlı ürün geliştiren girişim",
        value: "AI bulut ajanı",
      },
      { state: "met", text: "Tüzel kişilik ve kurucu ekip", value: "3 kişilik ekip" },
      { state: "met", text: "Daha önce eşdeğer kredi almamış", value: "İlk başvuru" },
    ],
  },
  {
    id: "nvidia",
    name: "NVIDIA Inception",
    org: "NVIDIA",
    category: "hizlandirici",
    categoryLabel: "Hızlandırıcı",
    icon: "rocket_launch",
    typeLabel: "Hızlandırıcı",
    hasAmount: false,
    amountText: "GPU + yazılım indirimi",
    amountSub: "VC ağına erişim",
    curCode: "",
    rate: "Donanım indirimi",
    status: "always",
    statusLabel: "Sürekli açık",
    deadlineText: "Sürekli başvuru",
    deadlineDays: null,
    sourceLink: "nvidia.com/startups",
    sourceHref: "https://www.nvidia.com/en-us/startups/",
    updated: "27 Haz 2026",
    elig: { state: "full", score: 88, label: "Uygun" },
    summary:
      "Doğrudan nakit kredi değil; GPU/yazılım indirimleri, teknik kaynaklar ve VC ağına erişim sağlar. Genellikle diğer bulut kredilerinin önünü açan ilk kapıdır.",
    criteria: [
      { icon: "memory", label: "Alan", value: "AI / derin teknoloji" },
      { icon: "rocket_launch", label: "Aşama", value: "Tüm aşamalar" },
      { icon: "groups", label: "Avantaj", value: "VC ağı" },
      { icon: "public", label: "Bölge", value: "Global" },
    ],
    conditions: [
      {
        state: "met",
        text: "Yapay zekâ / GPU yoğun ürün geliştiriyor",
        value: "AI çıkarım iş yükü",
      },
      { state: "met", text: "Tüzel kişiliği olan girişim", value: "Nova AI A.Ş." },
    ],
  },
  {
    id: "marka",
    name: "MARKA Proje Teklif Çağrısı",
    org: "Doğu Marmara Kalkınma Ajansı",
    category: "kamu",
    categoryLabel: "Kalkınma Ajansı",
    icon: "account_balance",
    typeLabel: "Hibe",
    hasAmount: true,
    amountText: "250.000–2.000.000",
    amountSub: "proje bütçesi",
    curCode: "TRY",
    rate: "%75'e kadar hibe",
    status: "open",
    statusLabel: "Açık",
    deadlineText: "Son başvuru 30 Eyl 2026",
    deadlineDays: 95,
    sourceLink: "marka.org.tr",
    sourceHref: "https://www.marka.org.tr",
    updated: "27 Haz 2026",
    elig: { state: "partial", score: 80, label: "1 koşul eksik" },
    summary:
      "Doğu Marmara bölgesindeki (Düzce dahil) işletmelere yönelik bölgesel proje teklif çağrısı. Teknoloji ve Ar-Ge odaklı projeler önceliklidir; eş finansman koşulu vardır.",
    criteria: [
      { icon: "location_on", label: "Bölge", value: "Doğu Marmara" },
      { icon: "memory", label: "Öncelik", value: "Teknoloji / Ar-Ge" },
      { icon: "apartment", label: "Ölçek", value: "KOBİ" },
      { icon: "event", label: "Durum", value: "Çağrı açık" },
    ],
    conditions: [
      { state: "met", text: "Doğu Marmara bölgesinde faaliyet", value: "Düzce — bölge içinde" },
      { state: "met", text: "Teknoloji / Ar-Ge odaklı proje", value: "AI yazılım projesi" },
      { state: "met", text: "KOBİ ölçeğinde işletme", value: "3 çalışan" },
      {
        state: "unmet",
        text: "Proje bütçesinin en az %25'i eş finansman (öz kaynak)",
        value: "Henüz planlanmadı",
        hint: "Bütçenin yaklaşık dörtte birini öz kaynaktan karşılaman gerekiyor. Gravio, eş finansmanı KOSGEB faizsiz kredisiyle birleştiren bir plan önerebilir.",
      },
    ],
  },
  {
    id: "kosgeb",
    name: "KOSGEB Girişimci Destek Programı",
    org: "KOSGEB",
    category: "kamu",
    categoryLabel: "Kamu Desteği",
    icon: "account_balance",
    typeLabel: "Hibe + Kredi",
    hasAmount: true,
    amountText: "1.500.000",
    amountSub: "TL'ye kadar",
    curCode: "TRY",
    rate: "%80 hibe + faizsiz kredi",
    status: "always",
    statusLabel: "Sürekli açık",
    deadlineText: "Sürekli (eğitim şartlı)",
    deadlineDays: null,
    sourceLink: "kosgeb.gov.tr",
    sourceHref: "https://www.kosgeb.gov.tr",
    updated: "27 Haz 2026",
    elig: { state: "partial", score: 70, label: "1 koşul eksik" },
    summary:
      "Yeni kurulan işletmelere kuruluş ve makine-teçhizat giderleri için geri ödemesiz ve geri ödemeli destek sağlar. Başvuru için Girişimcilik Eğitimi sertifikası gerekir.",
    criteria: [
      { icon: "storefront", label: "Hedef", value: "Yeni işletme" },
      { icon: "school", label: "Şart", value: "Girişimcilik eğitimi" },
      { icon: "apartment", label: "Ölçek", value: "KOBİ" },
      { icon: "flag", label: "Yerleşik", value: "Türkiye" },
    ],
    conditions: [
      { state: "met", text: "Yeni kurulmuş işletme", value: "Kuruluş < 1 yıl" },
      { state: "met", text: "KOSGEB veri tabanına kayıt", value: "Kayıt yapılabilir" },
      {
        state: "unmet",
        text: "KOSGEB onaylı Girişimcilik Eğitimi sertifikası",
        value: "Henüz alınmadı",
        hint: "Ücretsiz e-Akademi Girişimcilik Eğitimi'ni tamamlayıp sertifika alman gerekiyor — yaklaşık 1 hafta. Gravio takvimine ekleyebilir.",
      },
    ],
  },
  {
    id: "teknopark",
    name: "Teknopark Vergi İstisnası",
    org: "Sanayi ve Teknoloji Bakanlığı",
    category: "vergi",
    categoryLabel: "Vergi & Lokasyon",
    icon: "percent",
    typeLabel: "Vergi Avantajı",
    hasAmount: false,
    amountText: "Gelir & kurumlar vergisi istisnası",
    amountSub: "SGK + gümrük muafiyeti",
    curCode: "",
    rate: "Kazanç vergisi istisnası",
    status: "always",
    statusLabel: "Sürekli",
    deadlineText: "Sürekli (lokasyon şartlı)",
    deadlineDays: null,
    sourceLink: "sanayi.gov.tr",
    sourceHref: "https://www.sanayi.gov.tr",
    updated: "27 Haz 2026",
    elig: { state: "locked", score: 40, label: "Şu an uygun değil" },
    summary:
      "Teknoloji Geliştirme Bölgesi'nde (Teknopark) faaliyet gösteren firmalara gelir/kurumlar vergisi istisnası, personel için gelir vergisi stopajı ve SGK desteği sağlar. Lokasyon koşulu vardır.",
    criteria: [
      { icon: "location_on", label: "Koşul", value: "Teknoparkta kayıt" },
      { icon: "memory", label: "Alan", value: "Ar-Ge / yazılım" },
      { icon: "receipt_long", label: "Avantaj", value: "Vergi istisnası" },
      { icon: "badge", label: "Ek", value: "SGK desteği" },
    ],
    conditions: [
      {
        state: "met",
        text: "Ar-Ge / yazılım faaliyeti yürütüyor",
        value: "AI yazılım geliştirme",
      },
      {
        state: "unmet",
        text: "Bir Teknopark / TGB'de kayıtlı ofis",
        value: "Şu an Teknopark dışında",
        hint: "Bu avantaj için bir Teknopark'ta yer alman gerekiyor. Düzce Teknopark veya yakın bölgelerdeki TGB'lere başvurabilirsin — uygun olunca bu destek otomatik açılır.",
      },
    ],
  },
];

export function getProgram(id: string): Program {
  const p = PROGRAMS.find((x) => x.id === id);
  if (!p) throw new Error(`Program bulunamadı: ${id}`);
  return p;
}
